site: brio
url: https://brio.seeread.info
title: brio
description: links and ephemera
twitter:
  username: seereadnow
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  tags:
    output: true
    permalink: /tag/:name/
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"

prose:
  media: "assets/img"
  metadata:
    _pages:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "text"
          value: "page"
          label: "layout"
    _tags:
      - name: "slug"
        field:
          element: "text"
          label: "Slug"
      - name: "name"
        field:
          element: "text"
          label: "Name"
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "summary"
        field:
          element: "textarea"
          label: "Summary"
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
      - name: "layout"
        field:
          element: "text"
          value: "post"
          label: "Layout"
      - name: "tags"
        field:
          element: "multiselect"
          label: " Tags"
          placeholder: "Choose Tags"
          options:
            - name: "hack"
              value: "hack"
            - name: "geo"
              value: "geo"
      - name: "last_updated"
        field:
          element: "text"
          value: CURRENT_DATETIME
          label: "Last Updated"
      - name: "published"
        field:
          element: "checkbox"
          value: false
          label: "Published"
